/**
 * Mock provider — deterministic, keyless. For local dev and tests so the full
 * pipeline (orchestration, persistence, verdict gate, logging) runs end-to-end
 * without real keys or token spend. Returns valid specialist/chairwoman envelopes.
 *
 * It is NEVER a silent fallback for a real provider: a specialist is only mocked
 * when its roster row is explicitly set to provider 'mock'.
 */

export async function callMock({ purpose, user }) {
  const content = purpose === 'chairman'
    ? chairwomanEnvelope(user)
    : specialistEnvelope()

  // Rough token estimate (~4 chars/token) so usage tallies are non-null in dev.
  const inputTokens = Math.ceil((user?.length ?? 0) / 4)
  const outputTokens = Math.ceil(content.length / 4)

  return { content, inputTokens, outputTokens, httpStatus: 200 }
}

function specialistEnvelope() {
  return JSON.stringify({
    verdict: 'approve_with_caveats',
    verdict_rationale: '(mock) within range but watch portion size and sodium.',
    concerns: [
      { severity: 'low', issue: '(mock) sodium near upper guidance', evidence: 'mock provider' },
    ],
    suggestions: [
      { change: '(mock) finish with lemon and herbs instead of salt', rationale: 'flavor without sodium', preserves_intent: true },
    ],
  })
}

function chairwomanEnvelope(user) {
  const sourceHint = typeof user === 'string' && user.includes('SOURCE RECIPE')
    ? 'Adapted from the provided source recipe.'
    : 'Adapted recipe.'

  return JSON.stringify({
    recipe_markdown: `# Adapted Recipe (mock)\n\n${sourceHint}\n\n## Loadout\n- (mock ingredients)\n\n## Method\n1. (mock steps)\n\n_Generated by the mock provider for development._`,
    verdict: 'approved_with_caveats',
    verdict_summary: '(mock) approved with minor caveats from the committee.',
    caveats: ['(mock) serve a moderate portion', '(mock) season with acid and herbs, not salt'],
    warning_items: [],
    clinician_flags: [],
  })
}
